### ISSUE TITLE
is there touchpad support, ie. can I access wii U settings with this?

### ISSUE THREAD

**Issue by gleparc** [rolandoislas/drc-sim-client#1]
Hi,

I have a wii U without gamepad, and I was wondering if I can use this to access the settings menu in the wii u?  I heard that settings requires the touchpad functionality, and I wonder if that is possible with your mobile client.

Thank you for taking the time to share the code!

**Comment by opencma** [comment]
Yes, there is touch input via a mouse click or actual touch on the Android client.
