### ISSUE TITLE
Add way to clear/remove control.

### ISSUE THREAD

**Issue by Grntrenchman** [rolandoislas/drc-sim-client#15]
I accidentally set a control for two settings, and see no way to clear either a individual control, or all.

Maybe long press clears?
Edit: I can't tag? Should be enhancement?

**Comment by opencma** [comment]
I was considering having an input screen appear when an input config option was pressed. I think that would be more user-friendly as it can have buttons for unbinding and reverting to default.

**Comment by Grntrenchman** [comment]
Oh, by all means, that sounds much better. I'm no dev, so take my comments with (more than) a grain of salt.
