### ISSUE TITLE
Some OTHER controller input not working.

### ISSUE THREAD

**Issue by Grntrenchman** [rolandoislas/drc-sim-client#16]
So now buttons are fine, axis are good, but no pov/hat/dpad. It doesn't register as buttons.

I will tool around and try to find out what I get as input from the controller.

**Comment by Grntrenchman** [comment]
![screenshot_2017-06-05-15-06-51](https://cloud.githubusercontent.com/assets/29195872/26805418/b1e0d064-4a00-11e7-841b-6fab63a2f419.png)

The hat/dpad is a axis for me.

**Comment by Grntrenchman** [comment]
Found the issue: same file. Stops enumerating axis after 3, so sticks work (0,1,2,3) but no dpad.

**Comment by opencma** [comment]
The direction buttons only look for a d-pad, not a specific direction, when polling for input. If there is only one, all direction mappings (up/down/left/right) not related to the joystick should be `0`. I will look into implementing the d-pad directions as normal buttons.

Edit: I did not realize the d-pad was treated as an axis.

**Comment by Grntrenchman** [comment]
Looks like this'll be more than a one-line fix... I see in controlcontroller.java that it is hard coded to a pov and 4 axis. Have to figure out how to allow either button/pov/axis for the same control.

The easiest way to implement (since you want to add a dialog) would to be to sanitize the input filters, allowing axis/hat/buttons to work for any control. There is a wild range of controllers, and no telling how any is configured before they show up.
