### ISSUE TITLE
wii u wants to upgrade gamepad - region incompatible?

### ISSUE THREAD

**Issue by gleparc** [rolandoislas/drc-sim-client#3]
I have got the backend and the java client to work the first few times. With the client I was able to access Wii U settings and change my internet connection settings.

After one day the Wii U is now asking to update the gamepad, but I get an error 165-9901 and the screen says the gamepad is not region compatible (I am in Europe) and that it must do a reset. 

Is there a way to set the region for the gamepad? or the version of the gamepad firmware?

**Comment by opencma** [comment]
The current firmware details are hard coded into the backend. I will look into updating then to include a PAL version.

Edit: The updated [backend dev branch](https://github.com/rolandoislas/drc-sim/tree/develop) has version data stripped. An NTSC Wii U does not seem to mind the lack of version info.

**Comment by gleparc** [comment]
Thanks for looking into this! I'm really impressed with drc-sim-client. Now I see what you are trying to accomplish with the server-client setup.

does the backend you made use libdrc?  I grepped the drc-sim git pull that I had, but couldn't find any reference to libdrc (sorry for dumb questions - I am a noob to this). I had a look at the libdrc source and in the device-config.h and device-config.cpp files there are region settings:

~/libdrc $ grep -r -i region
include/drc/internal/device-config.h:  enum Region {
include/drc/internal/device-config.h:    kRegionJapan = 0x0,
include/drc/internal/device-config.h:    kRegionNorthAmerica = 0x1,
include/drc/internal/device-config.h:    kRegionEurope = 0x2,
include/drc/internal/device-config.h:    kRegionChina = 0x3,
include/drc/internal/device-config.h:    kRegionSouthKorea = 0x4,
include/drc/internal/device-config.h:    kRegionTaiwan = 0x5,
include/drc/internal/device-config.h:    kRegionAustralia = 0x6,
include/drc/internal/device-config.h:    kRegionUnsupported = 0xffffffff,

**Comment by opencma** [comment]
The backend is a fork of memahaxx's (the group that made libdrc) drc-sim. It was originally a prototype for features that were to be added to libdrc, however, it does not use libdrc.

**Comment by opencma** [comment]
Patch for the European Wii U confirmed working in rolandoislas/drc-sim#10.
