### ISSUE TITLE
Linux version not opening (Ubuntu)

### ISSUE THREAD

**Issue by BioThrust** [rolandoislas/drc-sim-client#31]
I downloaded the jar file expecting it to be like how it was on windows. I HAD installed java, yet when I opened the file nothing popped up. I then ran it in the terminal, and it said something about illegal reflective access warning. What should i do?

**Comment by M3KAI5ER44** [comment]
I want to know what the solution was, due to me having the same issue.

**Comment by BioThrust** [comment]
So fo 

> I want to know what the solution was, due to me having the same issue.

For those having the same issue, the problem was that any version of jre past 8 has some restrictions which makes it not work. You need to use jre 8
