### ISSUE TITLE
Audio Device Creation Crash

### ISSUE THREAD

**Issue by opencma** [rolandoislas/drc-sim-client#5]
See [drc-sim#12](https://github.com/rolandoislas/drc-sim/issues/12#issuecomment-289276582)

**Comment by opencma** [comment]
I cannot reproduce the error. I am going to assume this is a result of system audio being misconfigured.

**Comment by Flumper** [comment]
Yeah I have been reading that java is very picky about certain audio configs, but I dont know enough yet to do anything about it. Will keep reading up on it.

Just a quick question, would it make a difference if it was compiled without sound or not looking for audio devices or is that a built in part of java that cant be changed? I will only be using this for settings personally so sound isnt an issue for me.

**Comment by opencma** [comment]
Version [v1.1-beta-1](https://github.com/rolandoislas/drc-sim-client/releases/tag/v1.1-beta-1) should ignore audio errors.
