### ISSUE TITLE
missing home button and +/- buttons from desktop client

### ISSUE THREAD

**Issue by gleparc** [rolandoislas/drc-sim-client#6]
Dear Roland,  I just noticed, I cannot find in the keyboard/controller configuration settings, any options to set the home button or the +/- buttons on the gamepad controller.  The Android client offers at least the home button.

**Comment by opencma** [comment]
The settings list can be dragged to scroll. They should be at the bottom. Also, controllers will only be detected when the client starts; hotplugging is not supported.
