### ISSUE TITLE
gamepad "blow" button like in Cemu emulator

### ISSUE THREAD

**Issue by gleparc** [rolandoislas/drc-sim-client#7]
Hi Roland, 

Just read that CEMU emulator has a button option to emulate the "blow" on the mic for Captain Toad games. I don't know if this could be an added button in the drc-sim-client?

Thanks for all the great work, btw

**Comment by opencma** [comment]
I am improving the general data handling, but I will look into this soon.

**Comment by opencma** [comment]
[Halfway there](https://cloud.githubusercontent.com/assets/6559115/25077173/23d4a58e-22dc-11e7-9239-339d181198b1.png)

**Comment by opencma** [comment]
Implemented in [v1.5-beta](https://github.com/rolandoislas/drc-sim-client/releases/tag/v1.2-beta).

Random audio noise is generated and the Wii U registers it as input. I do not have any games that make use of the microphone "blow" mechanic, so I cannot test to see if it registers correctly.

**Comment by gleparc** [comment]
I can confirm it works with the Captain Toad game.
